//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLeasing.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarLeasingEntities : DbContext
    {
        public CarLeasingEntities()
            : base("name=CarLeasingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dystans> dystans { get; set; }
        public virtual DbSet<firma> firma { get; set; }
        public virtual DbSet<kolor> kolor { get; set; }
        public virtual DbSet<marka> marka { get; set; }
        public virtual DbSet<model> model { get; set; }
        public virtual DbSet<nadwozie> nadwozie { get; set; }
        public virtual DbSet<okres> okres { get; set; }
        public virtual DbSet<opona> opona { get; set; }
        public virtual DbSet<paliwo> paliwo { get; set; }
        public virtual DbSet<parametr> parametr { get; set; }
        public virtual DbSet<platnosc> platnosc { get; set; }
        public virtual DbSet<rola> rola { get; set; }
        public virtual DbSet<samochod> samochod { get; set; }
        public virtual DbSet<sezon> sezon { get; set; }
        public virtual DbSet<siedzenie> siedzenie { get; set; }
        public virtual DbSet<silnik> silnik { get; set; }
        public virtual DbSet<skrzynia> skrzynia { get; set; }
        public virtual DbSet<uzytkownik> uzytkownik { get; set; }
        public virtual DbSet<zamowienie> zamowienie { get; set; }
        public virtual DbSet<zdjecie> zdjecie { get; set; }
        public virtual DbSet<status> status { get; set; }
    }
}
