//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLeasing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class opona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public opona()
        {
            this.parametr = new HashSet<parametr>();
        }
    
        public int id_opona { get; set; }
        [Required(ErrorMessage = "Podaj nazwê")]
        public string nazwa { get; set; }
        public int firma_id_firma { get; set; }
        public int sezon_id_sezon { get; set; }
    
        public virtual firma firma { get; set; }
        public virtual sezon sezon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<parametr> parametr { get; set; }
    }
}
