//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLeasing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public parametr()
        {
            this.samochod = new HashSet<samochod>();
        }
    
        public int id_parametr { get; set; }
        public string opis { get; set; }
        public int rok_produkcji { get; set; }
        public int przebieg { get; set; }
        public int pojemnosc_bagaznika { get; set; }
        public int siedzenie_id_siedzenie { get; set; }
        public int opona_id_opona { get; set; }
        public int skrzynia_id_skrzynia { get; set; }
        public int nadwozie_id_nadwozie { get; set; }
        public int model_id_model { get; set; }
    
        public virtual model model { get; set; }
        public virtual nadwozie nadwozie { get; set; }
        public virtual opona opona { get; set; }
        public virtual siedzenie siedzenie { get; set; }
        public virtual skrzynia skrzynia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<samochod> samochod { get; set; }
    }
}
