//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLeasing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class silnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public silnik()
        {
            this.model = new HashSet<model>();
        }
    
        public int id_silnik { get; set; }
        public double moc { get; set; }
        public Nullable<double> spalanie { get; set; }
        public double pojemnosc { get; set; }
        public double emisja { get; set; }
        public double przyspieszenie { get; set; }
        public int paliwo_id_paliwo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<model> model { get; set; }
        public virtual paliwo paliwo { get; set; }
    }
}
