//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLeasing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class uzytkownik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uzytkownik()
        {
            this.zamowienie = new HashSet<zamowienie>();
        }
    
        public int id_uzytkownik { get; set; }
        [Required(ErrorMessage = "Podaj imiê")]
        public string imie { get; set; }
        [Required(ErrorMessage = "Podaj nazwisko")]
        public string nazwisko { get; set; }
        [Required(ErrorMessage = "Podaj email")]
        public string email { get; set; }
        [Required(ErrorMessage = "Podaj telefon")]
        public string telefon { get; set; }
        [Required(ErrorMessage = "Podaj has³o")]
        public string haslo { get; set; }
        public int rola_id_rola { get; set; }
    
        public virtual rola rola { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zamowienie> zamowienie { get; set; }
    }
}
