//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLeasing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zdjecie
    {
        public int id_zdjecie { get; set; }
        public string url { get; set; }
        public int samochod_id_samochod { get; set; }
    
        public virtual samochod samochod { get; set; }
    }
}
